name: LoopLine Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # enable manual trigger of the workflow

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-15
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version

      - name: List available simulators
        run: |
            xcrun simctl list devices available

      - name: Run unit tests
        run: |
          xcodebuild test \
            -project LoopLine.xcodeproj \
            -scheme LoopLine \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
            -only-testing:LoopLineTests \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults/UnitTests.xcresult \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: TestResults/UnitTests.xcresult
          if-no-files-found: error

  ui-tests:
    name: UI Tests
    runs-on: macos-15
    timeout-minutes: 10
    needs: unit-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version

      - name: Boot simulator (optional, erhöht Stabilität)
        run: |
          xcrun simctl boot "iPhone 17" || true

      - name: Run UI tests
        run: |
          xcodebuild test \
            -project LoopLine.xcodeproj \
            -scheme LoopLine \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
            -only-testing:LoopLineUITests \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults/UITests.xcresult \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload UI test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: TestResults/UITests.xcresult
          if-no-files-found: error